sudo: false
language: node_js
node_js:
  - 10
  - 11
  - 12
before_install:
  - export TZ=America/New_York
cache: yarn
install:
  - yarn --ignore-engines
script:
  - npm run lint
  - npm run test
after_script:
  - npm run coverage